### ISSUE TITLE
Steering angles file

### ISSUE THREAD

**Issue by harsmac** [pmwenzel/carla-domain-adaptation#1]
Which of the folders is of the original weather in the CARLA simulation. Also, not all folders seem to be present in the zipped file. The original steering angles also seem to be missing.

**Comment by pmwenzel** [comment]
Sorry for the late reply, w0 is the original weather from the CARLA simulator. The other folders are the one generated by CycleGANs. Only the weathers used to train the networks are present in the zipped file. We don't provide steering angles yet. This is only the dataset for the domain adaptation.
